// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC62FzpvePg-qnWAmLcXJXOGdS_NEZ9iSM',
    appId: '1:601212857943:web:3492930612f7362a42fd12',
    messagingSenderId: '601212857943',
    projectId: 'my-ledger-76727',
    authDomain: 'my-ledger-76727.firebaseapp.com',
    storageBucket: 'my-ledger-76727.appspot.com',
    measurementId: 'G-NXVEX3K4YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq0Fpp2i8Wq4MvFzKS1kmVhsZTpB0Mli4',
    appId: '1:601212857943:android:245180e64c9267f042fd12',
    messagingSenderId: '601212857943',
    projectId: 'my-ledger-76727',
    storageBucket: 'my-ledger-76727.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzAdoHn2rJhawvwq4U774WRD1E4uJqXts',
    appId: '1:601212857943:ios:e9d30de7da93101b42fd12',
    messagingSenderId: '601212857943',
    projectId: 'my-ledger-76727',
    storageBucket: 'my-ledger-76727.appspot.com',
    androidClientId: '601212857943-9da842lui3gjdjmaeov8ed2hiqprskaa.apps.googleusercontent.com',
    iosClientId: '601212857943-tpq0bhrqbqe9atb655u65srlusp8a477.apps.googleusercontent.com',
    iosBundleId: 'com.example.agoraTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzAdoHn2rJhawvwq4U774WRD1E4uJqXts',
    appId: '1:601212857943:ios:e9d30de7da93101b42fd12',
    messagingSenderId: '601212857943',
    projectId: 'my-ledger-76727',
    storageBucket: 'my-ledger-76727.appspot.com',
    androidClientId: '601212857943-9da842lui3gjdjmaeov8ed2hiqprskaa.apps.googleusercontent.com',
    iosClientId: '601212857943-tpq0bhrqbqe9atb655u65srlusp8a477.apps.googleusercontent.com',
    iosBundleId: 'com.example.agoraTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC62FzpvePg-qnWAmLcXJXOGdS_NEZ9iSM',
    appId: '1:601212857943:web:3492930612f7362a42fd12',
    messagingSenderId: '601212857943',
    projectId: 'my-ledger-76727',
    authDomain: 'my-ledger-76727.firebaseapp.com',
    storageBucket: 'my-ledger-76727.appspot.com',
    measurementId: 'G-NXVEX3K4YB',
  );

}